CREATE DATABASE TestBrq;
GO

USE TestBrq;
GO

CREATE TABLE Endereco(
	IdEndereco INT PRIMARY KEY IDENTITY,
	Cep VARCHAR (8) NOT NULL,
	Endereco VARCHAR(200) NOT NULL,
	Cidade VARCHAR (100) NOT NULL,
	Estado VARCHAR (100) NOT NULL,
	Numero VARCHAR (20) NOT NULL,
	Complemento VARCHAR(200)
);
GO 

CREATE TABLE DadosPessoais(
	IdDadosPessoais INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL,
	Sobrenome VARCHAR(200) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco)
);

